[tool.poetry]
name = "jfc-data"
version = "0.1.0"
description = ""
authors = ["fariz.tumbuan <fariz.tumbuan@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
