# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='jmdict-wrapper',
    version='0.1.0',
    description='Python wrapper for JMDict-XML file.',
    python_requires='==3.*,>=3.6.0',
    author='fariz.tumbuan',
    author_email='fariz.tumbuan@gmail.com',
    license='MIT',
    packages=['jmdict', 'jmdict.xml'],
    package_dir={"": "."},
    package_data={},
    install_requires=['beautifulsoup4==4.*,>=4.9.3', 'lxml==4.*,>=4.6.1'],
    extras_require={"dev": ["black==20.*,>=20.8.0.b1"]},
)
